# Generated by Django 3.2 on 2021-04-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0002_auto_20210415_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Heroku', 'Heroku'), ('GoogleCloud', 'GoogleCloud')], default='AWS', max_length=100),
        ),
    ]
